name: Deploy Production

on:
  # Trigger the workflow on push or pull request,
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  # This workflow contains a single job called "deploy"/.
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
          cache: 'npm'
      - name: Create .env file
        run: echo "${{secrets.ENV_PRODUCTION}}" > .env
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
